package string;

/**
 * 
 * @author raychen
 * Problem:
 * Write a function that given a sequence and a number b between [-10,10] return a new sequence. 
 * Sequences are generated by this: http://en.wikipedia.org/wiki/Look-and-say_sequence 
 * a number b if equal to 0 the function will return the input sequence 
 * Valid sequences: 1 11 21 1211 111221 ... 
 * Example: input: 1211, +1 output: 111221 
 * Example: input: 111221, -1 output: 1211
 */

public class CountAndSay {
    public String countAndSay(String input, int num) {
        StringBuilder output = new StringBuilder();
        return output.toString();
    }
}
